### ISSUE TITLE
Web hook reporting doesn't mark as reported.

### ISSUE THREAD

**Issue by emillly-b** [emillly-b/Saturn-Bot#13]
Error Message
System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace
at GenericBot.CommandModules.InfoModule.<>c.<Load>b0_5(EmbedFooterBuilder footer) in /home/emillly/Saturn-Bot/Saturn-Bot/GenericBot/CommandModules/InfoModule.cs:line 73
at Discord.EmbedBuilder.WithFooter(Action`1 action)
at GenericBot.CommandModules.InfoModule.<>cDisplayClass0_0.<<Load>b__4>d.MoveNext() in /home/emillly/Saturn-Bot/Saturn-Bot/GenericBot/CommandModules/InfoModule.cs:line 66
--- End of stack trace from previous location ---
at GenericBot.Entities.Command.ExecuteCommand(ParsedCommand command) in /home/emillly/Saturn-Bot/Saturn-Bot/GenericBot/Entities/Command.cs:line 69
Location
Emi's Dev Server (882342067341246534) - #general (882342067341246537)
Author
emillly#1014 (341275030941859850)
Message
>info
**Count
5**
**Reported
False**
**Today at 6:19 AM**

**Comment by emillly-b** [comment]
fixed in dababa3
